application: macaadamlazim
version: 6
runtime: python
api_version: 1

handlers:

- url: /players.*
  script: players.py

- url: /static
  static_dir: static

- url: .*
  script: index.py


