application: macaadamlazim
version: 1
runtime: python
api_version: 1

handlers:
  
- url: /onlinedebug.*
  script: onlinedebug/onlinedebug.py   
  
- url: /listfiles.*
  script: listfiles.py 
  
- url: /static
  static_dir: static
  
- url: .*
  script: index.py 
   
  
